# Step 1: Base image
FROM node:18-alpine as base
WORKDIR /app

# Step 2: Install dependencies
FROM base AS deps
COPY fawatir_frontend/package.json ./fawatir_frontend/
WORKDIR /app/fawatir_frontend
RUN npm install

# Step 3: Build application
FROM base AS builder
COPY --from=deps /app/fawatir_frontend/node_modules ./fawatir_frontend/node_modules
COPY fawatir_frontend ./fawatir_frontend
WORKDIR /app/fawatir_frontend

ENV NEXT_TELEMETRY_DISABLED 1
RUN npm run build

# Step 4: Production runner
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/fawatir_frontend/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/fawatir_frontend/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/fawatir_frontend/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]
