version: '3.8'

services:
  frontend:
    build:
      context: ./fawatir_frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./fawatir_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fawatir_backend:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    command: >
      sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    entrypoint: ["/bin/sh", "-c"]
    volumes:
      - ollama_models:/root/.ollama
    command: >
      sh -c "ollama serve & sleep 5 && ollama pull qwen2.5:3b-instruct && wait"

volumes:
  ollama_models:
