# Generated by Django 6.0.7 on 2026-07-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aiconversation_user_auditlog_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
