# Generated by Django 6.0.7 on 2026-08-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client_metadata_product_metadata_supplier_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='metadata',
        ),
    ]
