# Generated by Django 6.0.7 on 2026-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_client_metadata_remove_product_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='smtp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='twilio_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
