name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-docker-builds:
    name: Validate Docker Builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Build Django Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./fawatir_backend
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Build Next.js Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./fawatir-frontend-main
          file: ./Dockerfile.frontend
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
