name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-docker-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Build Django Backend
        uses: docker/build-push-action@v5
        with:
          context: ./fawatir_backend
          file: ./fawatir_backend/Dockerfile
          push: false

      - name: Test Build Next.js Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          push: false
